site_name: Monerodocs
site_url: https://www.md.monerodevs.org/
site_description: Project documentation with Markdown.
site_author: Monero Community

repo_url: https://github.com/plowsof/md/
edit_uri: blob/latest_mkdocs_test/docs/

theme:
  name: material
  #custom_dir: mkdocs-material/material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  logo: images/logo.png

nav:
  - Home: 'index.md'
  - Interacting:
    - Download: 'interacting/download-monero-binaries.md'
    - Verify: 'interacting/verify-monero-binaries.md'
    - Overview: 'interacting/overview.md'
    - Config file: 'interacting/monero-config-file.md'
    - monerod: 'interacting/monerod-reference.md'
    - monero-wallet-cli: 'interacting/monero-wallet-cli-reference.md'
    - monero-wallet-gui: 'interacting/monero-wallet-gui-reference.md'
    - monero-wallet-rpc: 'interacting/monero-wallet-rpc-reference.md'
    - monero-blockchain-export: 'interacting/monero-blockchain-export-reference.md'
    - monero-blockchain-import: 'interacting/monero-blockchain-import-reference.md'
  - Technical specs: 'technical-specs.md'
  - Cryptography:
      - Introduction: 'cryptography/introduction.md'
      - Asymmetric:
        - Introduction: 'cryptography/asymmetric/introduction.md'
        - Private keys: 'cryptography/asymmetric/private-key.md'
        - Public keys: 'cryptography/asymmetric/public-key.md'
        - Edwards25519 curve: 'cryptography/asymmetric/edwards25519.md'
        - Key image: 'cryptography/asymmetric/key-image.md'
      - Base58: 'cryptography/base58.md'
      - PRNG: 'cryptography/prng.md'
      - 'Keccak-256': 'cryptography/keccak-256.md'
  - Address:
      - Standard: 'public-address/standard-address.md'
      - Subaddress: 'public-address/subaddress.md'
      - Integrated: 'public-address/integrated-address.md'
  - Proof of Work:
      - What is PoW?: 'proof-of-work/what-is-pow.md'
      - PoW in Cryptocurrencies: 'proof-of-work/pow-in-cryptocurrencies.md'
      - CryptoNight: 'proof-of-work/cryptonight.md'
      - RandomX: 'proof-of-work/random-x.md'
  - Multisignature: 'multisignature.md'
  - Infrastructure:
      - Mainnet, stagenet, testnet: 'infrastructure/networks.md'
      - Tor onion seed nodes: 'infrastructure/tor-onion-p2p-seed-nodes.md'
      - MoneroPulse: 'infrastructure/monero-pulse.md'
  - Running a Node:
    # - On your Laptop: 'localhost-node.md'
    # - Remote Node: 'remote-node.md'
    # - Open Remote Node: 'open-remote-node.md'
    - Open Node + Tor Onion: 'running-node/open-node-tor-onion.md'
  - Cold storage:
      - Offline Transaction Signing: 'cold-storage/offline-transaction-signing.md'
  - Accepting Monero:
      - Overview: 'accepting-monero/overview.md'

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click
  - admonition
  - pymdownx.details

copyright: Copyright &copy; Monero Community. Contributors referenced under each file. Content is MIT Licensed.

hooks:
  - docs/hooks.py

plugins:
  #coolify does not clone the git repo deep enough
  #or issues with docker not copying .git folder
  - privacy
  - git-committers:
      repository: plowsof/md
      branch: latest_mkdocs_test
      token: !ENV ["GH_TOKEN"]
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: es
          name: Español
          build: true
        - locale: it
          name: Italiano
          build: true
        - locale: pl
          name: Polski
          build: true
        - locale: ar
          name: العربية
          build: true
        - locale: ru
          name: Русский
          build: true
        - locale: de
          name: Deutsch
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: pt
          name: Português
          build: true
        - locale: tr
          name: Türkçe
          build: true
        - locale: zh
          name: 中文 (简体)
          build: true
        - locale: zh-TW
          name: 中文 (繁體)
          build: true
        - locale: nb
          name: Norsk Bokmål
          build: true
  - git-revision-date-localized
  - search
  - redirects:
      redirect_maps:
        user-guide/plugins.md: dev-guide/plugins.md
        user-guide/custom-themes.md: dev-guide/themes.md
        user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
  - autorefs
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true

watch:
  - mkdocs
